project:
  name: cloudformation-infra-test
  regions:
    - ap-southeast-1
  parameters:
    KeyName: nt548-laq1254-key-v2
    AllowedSshCidr: 0.0.0.0/0
    ProjectName: cloudformation-infra-test

tests:
  infrastructure:
    template: ../templates/infrastructure.yaml