project:
  name: cloudformation-infra-test
  regions:
    - ap-southeast-1

tests:
  infrastructure:
    template: templates/infrastructure.yaml
    parameters:
      ProjectName: cloudformation-infra-test
      KeyName: nt548-laq1254-key-v2
      AllowedSshCidr: 0.0.0.0/0
