version: 0.2

phases:
  install:
    commands:
      - python -m pip install --upgrade pip
      - python -m pip uninstall -y setuptools
      - python -m pip install "setuptools<81"
      - python -m pip install cfn-lint
      - python -m pip install taskcat
      - python -c "import pkg_resources; print('pkg_resources OK')"
  pre_build:
    commands:
      - aws --version
      - cfn-lint --version
  build:
    commands:
      - cfn-lint cloudformation/templates/infrastructure.yaml
      - cd cloudformation && taskcat test run

artifacts:
  files:
    - cloudformation/templates/infrastructure.yaml
